name: plantas
services:
  database:
    image: 'postgres:15.1'
    restart: unless-stopped
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: nani
      POSTGRES_DB: plantas
    volumes:
      - plantas_data:/var/lib/postgresql/data
  
  api_plantas:
    build: code/
    depends_on:
      - database
    ports:
      - "5000:5000"
    volumes:
      - "./code/:/python-docker"
    env_file:
      - ./code/.env.docker
    

volumes:
  plantas_data:
